arb-dir: lib\config\l10n
template-arb-file: app_pl.arb
output-localization-file: localizations.dart
synthetic-package: false
preferred-supported-locales: [pl]
untranslated-messages-file: untranslated.json
output-class: AppLocalizations
